#!/bin/sh
#
# rxstack	Regina Stack daemon
#
# chkconfig:	345 80 30
# description:	Regina Stack daemon
# processname:	rxstack
# pidfile:	/var/run/rxstack.pid
# config:	/etc/sysconfig/rxstack

# source function library
. /etc/rc.d/init.d/functions

# Get network config
. /etc/sysconfig/network

# Get service config 
[ -f /etc/sysconfig/sysmond ] && . /etc/sysconfig/sysmond

# Check that networking is up.
if is_yes "${NETWORKING}"; then
	if [ ! -f /var/lock/subsys/network -a "$1" != stop -a "$1" != status ]; then
		msg_network_down sysmon
		exit 1
	fi
else
	exit 0
fi

start() {
	# Check if the service is already running?
	if [ ! -f /var/lock/subsys/sysmond ]; then
		msg_starting sysmon service
		daemon /usr/bin/sysmond -f $SYSMOND_CONFIG $SYSMOND_OPTIONS
		RETVAL=$?
		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/sysmond
	else
		msg_already_running sysmon
	fi
}

stop() {
	# Stop daemons.
	if [ -f /var/lock/subsys/sysmond ]; then
		msg_stopping sysmon 
		killproc /usr/bin/sysmond -15
		rm -f /var/lock/subsys/sysmond
	else
		msg_not_running sysmon 
	fi
}

RETVAL=0
case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	stop
   	start
  	;;
  reload)
  	if [ ! -f /var/lock/subsys/sysmond ]; then
		msg_reloading sysmon 
		killproc /usr/bin/sysmond -HUP
	else
		msg_not_running sysmon
	fi
	;;
  status)
	status sysmond
	RETVAL=$?
	;;
  *)
	msg_usage "$0 {start|stop|restart|reload|status}"
	exit 3
esac

exit $RETVAL
